### ISSUE TITLE
Fail to understand sub package (again)

### ISSUE THREAD

**Issue by RUSshy** [d-language-server/dls#71] opened 2020-03-12 01:49 UTC
DLS crash on startup:

```
[Error - 2:44:46 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
object.Exception@C:\Users\appveyor\AppData\Local\dub\packages\dub-1.19.0\dub\source\dub\packagemanager.d(258): Sub package "common:common" doesn't exist.
```

"common:common" should be: ""my_project:common" (see bellow)

Following project structure

```
my_project
    -> client
        src/
         dub.json: dependency: "my_project:common": { "path": "../common/", "version": "~master"},

    -> common
        src/
        dub.json

    -> dub.json: "subPackages": [ "client", "common"]
```

**Comment by LaurentTreguier** [comment] 2020-03-12 08:55
I haven't touched this part of the code in such a long time that I wouldn't be surprised if it was a regression from updating the dub library.
I'll look into this, maybe it could be fixed by simply upgrading to the new 1.20 version that just came out.

**Comment by LaurentTreguier** [comment] 2020-03-13 18:37
Looking at this again, I see what the problem is. When a subpackage depends on another subpackage, you don't need to explicitely specify the path, you can just do
```
dependency: "my_project:common": "*",
```
and it should build just fine. Inter-subpackage dependencies are used in DLS itsef, so I'm pretty sure this should work with your project as well

**Comment by RUSshy** [comment] 2020-03-13 19:09
Ah you are right, that solved the issue! thanks!

**Closed** 2020-03-13 19:09 UTC
